# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cvss.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cvss.proto',
  package='cvss',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ncvss.proto\x12\x04\x63vss\"]\n\x05\x45vent\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x1f\n\x03vul\x18\x03 \x01(\x0e\x32\x12.cvss.Event.VulTyp\"\x1a\n\x06VulTyp\x12\x07\n\x03XSS\x10\x00\x12\x07\n\x03SQL\x10\x01\"(\n\x07\x43VSSRes\x12\x0e\n\x06vector\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x32\x32\n\x07\x43VSSSvc\x12\'\n\tgetVector\x12\x0b.cvss.Event\x1a\r.cvss.CVSSResb\x06proto3')
)



_EVENT_VULTYP = _descriptor.EnumDescriptor(
  name='VulTyp',
  full_name='cvss.Event.VulTyp',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='XSS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SQL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=87,
  serialized_end=113,
)
_sym_db.RegisterEnumDescriptor(_EVENT_VULTYP)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='cvss.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='cvss.Event.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='cvss.Event.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vul', full_name='cvss.Event.vul', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENT_VULTYP,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=113,
)


_CVSSRES = _descriptor.Descriptor(
  name='CVSSRes',
  full_name='cvss.CVSSRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='cvss.CVSSRes.vector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='cvss.CVSSRes.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=155,
)

_EVENT.fields_by_name['vul'].enum_type = _EVENT_VULTYP
_EVENT_VULTYP.containing_type = _EVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['CVSSRes'] = _CVSSRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'cvss_pb2'
  # @@protoc_insertion_point(class_scope:cvss.Event)
  })
_sym_db.RegisterMessage(Event)

CVSSRes = _reflection.GeneratedProtocolMessageType('CVSSRes', (_message.Message,), {
  'DESCRIPTOR' : _CVSSRES,
  '__module__' : 'cvss_pb2'
  # @@protoc_insertion_point(class_scope:cvss.CVSSRes)
  })
_sym_db.RegisterMessage(CVSSRes)



_CVSSSVC = _descriptor.ServiceDescriptor(
  name='CVSSSvc',
  full_name='cvss.CVSSSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=157,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='getVector',
    full_name='cvss.CVSSSvc.getVector',
    index=0,
    containing_service=None,
    input_type=_EVENT,
    output_type=_CVSSRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CVSSSVC)

DESCRIPTOR.services_by_name['CVSSSvc'] = _CVSSSVC

# @@protoc_insertion_point(module_scope)
