# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/research/deployment

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - run:
          name: run tests
          command: |
            echo "test should be run here"
  deploy-job:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f6:c5:76:c0:74:c8:68:90:4a:24:94:e3:9f:11:48:50"
      - run:
          name: pulling to server
          command: |
            ssh root@128.199.75.109 'cd ~/research/Frogod && git pull origin master'
      - run:
          name: finishing deployment
          command: |
            ssh root@128.199.75.109 'cd ~/research/Frogod && python intercept.py'
      