# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/research/deployment

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - run:
          name: run tests
          command: |
            echo "test should be run here"

  deploy:
    machine:
      enabled: true

    working_directory: ~/research/deployment

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "70:a8:a0:75:5a:88:b5:03:3a:f9:c1:05:7c:17:8f:b0"
      - run:
          name: pulling to server
          command: |
            ssh $SSHUSER@$SSHSERVER 'cd ~/research/Frogod && git pull origin master'
      - run:
          name: finishing deployment
          command: |
            ssh $SSHUSER@$SSHSERVER 'cd ~/research/Frogod && python intercept.py'
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires: 
            - build
          filters:
            branches:
              only: master